name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
          - 'coqorg/coq:8.13'
          - 'coqorg/coq:8.12'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          install: ""
          after_install: ""
          script: make
          uninstall: ""

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
